#!/opt/apps/intel13/python/2.7.9/bin/python
''' Idev: Creates job, waits for run state, and ssh's to master node '''

# Basic shell:  ssh to a node, exit and kill job.  kfm 4/8/2015

import subprocess


def submit_job(job_script):
  print "sub_job"
# ...


__name__ == "__main__"

master_node = "c560-802"
job_id      = "5086035"

try:

  print "SSHing to a node"
  subprocess.call(['ssh','-Y',master_node])

except:
  print "Canceling Job -- from exception"
else:
  print "Canceling Job"
  subprocess.call(['scancel',job_id])



#http://www.python-course.eu/forking.php
#https://docs.python.org/2/library/sys.html
